import { randomUUID } from "crypto";
import { streamTts } from "./tts";
import { VoiceSession } from "./session";
import { PluginConfig } from "./types";

/**
 * Runs the agent with streaming TTS playback of response deltas.
 * Returns the full text generated by the agent.
 */
export async function runAgent(
  api: any,
  cfg: PluginConfig,
  session: VoiceSession,
  sttText: string,
): Promise<string> {
  let unsub: (() => void) | undefined;
  let fullText = "";

  try {
    const route = api.runtime.channel.routing.resolveAgentRoute({
      channel: "lyra",
      accountId: "default",
      peer: { kind: "direct", id: session.clientId },
      cfg: api.config,
    });

    // Sequential TTS queue to avoid overlapping audio playback
    let ttsQueue: Promise<void> = Promise.resolve();

    const flushDelta = (delta: string) => {
      const cleaned = delta
        .replace(/\[\[reply_to_current\]\]/g, "")
        .replace(/\[ASK\]/g, "")
        .trim();
      if (!cleaned || session.cancelRequested) return;
      ttsQueue = ttsQueue.then(async () => {
        if (session.cancelRequested) return;
        session.state = "speaking";
        await streamTts(cleaned, cfg.tts ?? {} as any, (chunk: Buffer) => {
          if (!session.cancelRequested && session.ws.readyState === 1) session.ws.send(chunk);
        });
      });
    };

    let resolveRun!: () => void;
    const runFinished = new Promise<void>((res) => { resolveRun = res; });

    // runId is only available after subagent.run() resolves — use a mutable variable
    // to buffer events that arrive before the runId is known
    let runId: string | null = null;
    let pendingEvents: any[] = [];

    const processEvent = (event: any) => {
      if (event.stream === "assistant" && event.data?.delta) {
        api.logger.info(
          `[lyra-ws] agent delta seq=${event.seq} delta="${event.data.delta}"`,
        );
        if (event.data.text) fullText = event.data.text;
        flushDelta(event.data.delta);
      } else if (event.stream === "lifecycle") {
        api.logger.info(
          `[lyra-ws] agent lifecycle phase="${event.data?.phase}" runId=${event.runId}`,
        );
        if (event.data?.phase === "end") resolveRun();
      } else {
        api.logger.info(
          `[lyra-ws] agent unknown stream="${event.stream}" seq=${event.seq} data=${JSON.stringify(event.data)}`,
        );
      }
    };

    // Register listener BEFORE firing the run to avoid missing early events
    unsub = api.runtime.events.onAgentEvent((event: any) => {
      api.logger.info(
        `[lyra-ws] onAgentEvent runId=${event.runId} stream=${event.stream} seq=${event.seq} (expected=${runId ?? "pending"})`,
      );
      if (runId === null) { pendingEvents.push(event); return; }
      if (event.runId !== runId) return;
      processEvent(event);
    });

    const { runId: id } = await api.runtime.subagent.run({
      sessionKey: route.sessionKey,
      message: sttText,
      deliver: false,
      idempotencyKey: randomUUID(),
    });

    runId = id;

    // Flush events that arrived before runId was available
    for (const event of pendingEvents) {
      if (event.runId === runId) processEvent(event);
    }
    pendingEvents = [];

    const timeout = new Promise<void>((_, reject) =>
      setTimeout(() => reject(new Error("agent run timed out")), 60_000),
    );
    await Promise.race([runFinished, timeout]);

    // Wait for the TTS queue to drain
    await ttsQueue;

    return fullText;
  } finally {
    unsub?.();
  }
}
